# Prometheus configuration for ClickUp integration monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # ClickUp API metrics (when /metrics endpoint is added)
  - job_name: 'clickup-api'
    static_configs:
      - targets: ['clickup-api:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MCP Server metrics (when /metrics endpoint is added)
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s